variables:
  DOCKER_RIGISTRY: registry.gitlab.com/maxwutw/tsmc_hackathon

image: $DOCKER_RIGISTRY:latest

stages:
  - install
  - test
  - build

install-dependencies:
  stage: install
  script:
    - echo "install dependencies"
    - apt update && apt install -y jq

testing:
  stage: test
  script:
    - echo "testing"

build-docker-image:
  stage: build
  before_script:
    - export IMAGE_VERSION=$(cat info.json | jq -r .version)
  script:
    - docker build --build-arg TARGET_NAME=VisionAssistant -t visionassistantserver:$IMAGE_VERSION .
    # - docker build --build-arg TARGET_NAME=FunctionCalling -t grounding-dino-server:$IMAGE_VERSION .

# push-to-registry:
#   stage: publish
