stages:
  - install
  - test
  - build

install-dependencies:
  stage: install
  script:
    - echo "install dependencies"
    - apt update && apt install -y jq

testing:
  stage: test
  script:
    - echo "testing"

build-docker-image:
  image: docker:20.10.16
  stage: build
  before_script:
    - export IMAGE_VERSION=$(cat info.json | jq -r .version)
  script:
    - docker build --build-arg TARGET_NAME=FunctionCalling -t grounding-dino-server:$IMAGE_VERSION .
    - docker build --build-arg TARGET_NAME=VisionAssistant -t vision-assistant-server:$IMAGE_VERSION .

# push-to-registry:
#   stage: publish
