image: $DOCKER_REGISTRY:latest

variables:
  DOCKER_REGISTRY: registry.gitlab.com/maxwutw/tsmc_hackathon
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - install
  - test
  - build

install-dependencies:
  stage: install
  script:
    - echo "install dependencies"
    - apt update && apt install -y jq

testing:
  stage: test
  script:
    - echo "testing"

build-docker-image:
  stage: build
  image: docker:latest
  before_script:
    - apt update && apt install -y jq
    - export IMAGE_VERSION=$(cat info.json | jq -r .version || echo "latest")
    - docker --version
  script:
    - docker build --build-arg TARGET_NAME=visionassistant -t visionassistantserver:$IMAGE_VERSION .
    - docker build --build-arg TARGET_NAME=groundingdino -t groundingdinoserver:$IMAGE_VERSION .
    - docker build --build-arg TARGET_NAME=inpainting -t inpaintingserver:$IMAGE_VERSION .
    - docker build --build-arg TARGET_NAME=imagen -t imagenserver:$IMAGE_VERSION .

# push-to-registry:
#   stage: publish
